# Generated by Django 3.2.12 on 2022-03-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crescendo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.ImageField(default=':\\Users\\86133\\WAD2_Crescendo\\static/playlist_images/image.jpg', upload_to=':\\Users\\86133\\WAD2_Crescendo\\static/playlist_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=':\\Users\\86133\\WAD2_Crescendo\\static/profile_images/image.jpg', upload_to=':\\Users\\86133\\WAD2_Crescendo\\static/profile_images'),
        ),
    ]
